services:
  Chatbot\ChatbotBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']
    autowire: true
    autoconfigure: true

  Chatbot\ChatbotBundle\Repository\:
    resource: '../../Repository'
    autowire: true
    autoconfigure: true